### ISSUE TITLE
Version 1.8 generates HTTP code 0

### ISSUE THREAD

**Issue by AugustoEst** [arduino-libraries/Temboo#10]
I'm using the Arduino MKR1000 (WiFi101) and the Yahoo.Weather.GetTemperature Choreo (and example).

The example code from Temboo works fine in **1.6** (HTTP Code 200), but exactly the same code generates HTTP Code 0 in **1.8**.

**Comment by cormacdriver-temboo** [comment]
That error means that your device is unable to establish a connection to Temboo. We've tried to reproduce the same error with the MKR1000 and v1.8 and haven't been able to i.e., things are working fine for us - the sketch works successfully on v1.6 and v1.8. 

If you'd like us to investigate further, please contact Temboo support and include your sketch. 

https://temboo.com/support
