### ISSUE TITLE
Minor changes needed to work on popular ESP8266 wifi arduino boards

### ISSUE THREAD

**Issue by ostersc** [arduino-libraries/Temboo#5]
I was able to get the arduino library to work on the ESP8266 wifi arduino boards, just by replacing all references of avr/pgmspace.h to pgmspace.h as described here:
https://forum.arduino.cc/index.php?topic=337186.0

Please incorporate support for this, as these are popular WiFi chips for arduino.

Thanks!

**Comment by ostersc** [comment]
I think this is the change you need:
#ifdef ARDUINO_ARCH_AVR
#include <avr/pgmspace.h>
#else
#include "pgmspace.h"
#endif

**Comment by cormacdriver-temboo** [comment]
Thanks for this. I'll duplicate the issue in our internal dev repo and close this issue out.
